### ISSUE TITLE
Client/Server failure with version 0.33 (single server)

### ISSUE THREAD

**Issue by flikka** [equinor/gordo#531]
Using gordo-deploy version 0.35.0 seems to fail when the client tries to do predictions. 
Versions: `gordo-model-server:0.33.0`

How to reproduce:
* Run a gordo project with deploy-version: 0.35.0
Error from server logs:
```[2019-10-11 10:15:13,012] DEBUG [gordo_components.server.server._log_time_taken:115] Total runtime for request: 0.05434798399983265s
[2019-10-11 10:15:13,012] INFO [werkzeug._log:122] 10.201.1.23 - - [11/Oct/2019 10:15:13] "POST /gordo/v0/v35/some-random-model/anomaly/prediction?format=parquet HTTP/1.1" 500 -
[2019-10-11 10:15:13,013] ERROR [gordo_components.server.server.log_exception:1891] Exception on /gordo/v0/v35/some-random-model/anomaly/prediction [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/gordo_components/server/utils.py", line 379, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/gordo_components/server/utils.py", line 305, in wrapper_method
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/gordo_components/server/views/anomaly.py", line 96, in post
    return self._create_anomaly_response(start_time)
  File "/usr/local/lib/python3.6/site-packages/gordo_components/server/views/anomaly.py", line 126, in _create_anomaly_response
    anomaly_df = g.model.anomaly(g.X, g.y, frequency=self.frequency)
  File "/usr/local/lib/python3.6/site-packages/gordo_components/model/anomaly/diff.py", line 127, in anomaly
    self.predict(X) if hasattr(self, "predict") else self.transform(X)
  File "/usr/local/lib/python3.6/site-packages/sklearn/compose/_target.py", line 225, in predict
    pred = self.regressor_.predict(X)
  File "/usr/local/lib/python3.6/site-packages/sklearn/utils/metaestimators.py", line 116, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sklearn/pipeline.py", line 422, in predict
    return self.steps[-1][-1].predict(Xt, **predict_params)
  File "/usr/local/lib/python3.6/site-packages/gordo_components/model/models.py", line 135, in predict
    return self.model.predict(X, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 909, in predict
    use_multiprocessing=use_multiprocessing)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 722, in predict
    callbacks=callbacks)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 393, in model_iteration
    batch_outs = f(ins_batch)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3740, in __call__
    outputs = self._graph_fn(*converted_inputs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1081, in __call__
    return self._call_impl(args, kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1121, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError:  You must feed a value for placeholder tensor 'dense_21_1/MatMul/ReadVariableOp/resource' with dtype resource
	 [[node dense_21_1/MatMul/ReadVariableOp/resource (defined at /site-packages/tensorflow_core/python/framework/ops.py:1751) ]] [Op:__inference_keras_scratch_graph_674]

Function call stack:
keras_scratch_graph
```

**Comment by flikka** [comment]
Close duplicate of #523
