### ISSUE TITLE
Exception from postgres reporter on ioc-1901

### ISSUE THREAD

**Issue by flikka** [equinor/gordo#930]
On ioc07jsv see the gordo ioc-1901, argo workflow ioc-1901-1581661405269-zw245, model builder ioc-1901-1581661405269-zw245-280927712

Gordo version: 0.50.0
```
[2020-02-14 06:30:37,962] INFO [gordo.reporters.postgres.report:75] Inserting machine c5f17844-2913-4a96-b34a-6e05248da252-9999 in sql
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3057, in execute_sql
    cursor.execute(sql, params or ())
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "machine_name"
DETAIL:  Key (name)=(c5f17844-2913-4a96-b34a-6e05248da252-9999) already exists.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gordo/reporters/postgres.py", line 79, in report
    dict_to_model(Machine, record, ignore_unknown=True).save()
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 6433, in save
    pk = self.insert(**field_dict).execute()
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 1845, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 1916, in execute
    return self._execute(database)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 2665, in _execute
    return super(Insert, self)._execute(database)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 2398, in _execute
    cursor = self.execute_returning(database)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 2405, in execute_returning
    cursor = database.execute(self)
  File "/usr/local/lib/python3.7/site-packages/playhouse/postgres_ext.py", line 477, in execute
    cursor = self.execute_sql(sql, params, commit=commit)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3064, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 2831, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3057, in execute_sql
    cursor.execute(sql, params or ())
peewee.IntegrityError: duplicate key value violates unique constraint "machine_name"
DETAIL:  Key (name)=(c5f17844-2913-4a96-b34a-6e05248da252-9999) already exists.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gordo/cli/cli.py", line 150, in build
    machine_out.report()
  File "/usr/local/lib/python3.7/site-packages/gordo/machine/machine.py", line 137, in report
    reporter.report(self)
  File "/usr/local/lib/python3.7/site-packages/gordo/reporters/postgres.py", line 81, in report
    raise PostgresReporterException(exc)
gordo.reporters.postgres.PostgresReporterException: duplicate key value violates unique constraint "machine_name"
DETAIL:  Key (name)=(c5f17844-2913-4a96-b34a-6e05248da252-9999) already exists.
```

**Comment by milesgranger** [comment]
Did this workflow have two or more machine names which were the same?

**Comment by epa095** [comment]
@milesgranger  no, what happened was that the MLflow reporter crashed *after* the postgres reporter had reported. And then the model-builder got restarted, and then on the second (and third and fourth and fifth) attempt we get these errors here from postgres, since the metadata is already stored (from that first model-builder which succseeded). So I guess the fix is to ignore these kinds of errors maybe?
